name: Build and Deploy ASP.NET MVC App to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "arjun-azure-dotnet-web-app"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "."      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '5.8.0'
  DOTNETSDK_VERSION: '3.1.302'
  RESOURCEGROUPNAME: "arjun-azure-dotnet-web-app-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "arjun-azure-dotnet-web-app-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "S1 Standard"

jobs:
  build:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION }}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: |
        cd Application
        nuget restore
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
    - name: Run MSBuild
      run: |
        cd Application
        msbuild .\SampleWebApplication.sln -p:Configuration=Release

    - name: Setup .NET sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env. DOTNETSDK_VERSION }}
    
    - name: Run unit tests
      run: | 
        cd Application\SampleWebApplication.UnitTests
        dotnet test bin\Release\*.UnitTests.dll --verbosity normal

    - name: Archive Application
      run: |
        Compress-Archive -Path ./Application/SampleWebApplication -DestinationPath ./buildartifacts/Application.zip

    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts

    - name: Archive ArmTemplates
      run: |
        Compress-Archive -Path ./ArmTemplates -DestinationPath ./deploymenttemplates/ArmTemplates.zip

    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: deploymenttemplates
